### ISSUE TITLE
Query GitHub for sponsorship links

### ISSUE THREAD

**Issue by mholt** [joshuabezaleel/go-support#1]
Great to see someone taking the initiative on this project!

Have you considered simply querying GitHub to see if the "Sponsor" link is on that repo? Then you don't have to maintain a list. (At least, for GitHub-enabled sponsorships. Which will probably quickly grow to be most of them.)

**Comment by TheGrum** [comment]
Also if no sponsor link found in canonical list or in the GitHub query, you could parse the README.md file and simply scan for links to certain known donation sites. If there is a patreon link, an opencollective link, a github/sponsor link, or a link whose lead-in text has Donate or Sponsor, grab that.  Since the included libraries will all have already been downloaded, the README.md files if they exist should all be on the local filesystem for easy grabbing, right?

**Comment by joshuabezaleel** [comment]
Hi @mholt & @TheGrum , truly sorry for the late reply. Thank you very much for taking your time to commenting here. Really appreciate it! :slightly_smiling_face: 

By the way, @mholt , I am huge fan of yours on what you do with caddy, thank you very much for your contribution to the community!! :tada: :tada: 

By querying, do you folks mean accessing via the REST API and parsing the content of the `.github/FUNDING.yml` file on each of the repositories? I tried to dig in to the GitHub GraphQL API and found out that `Sponsorable` is implemented only on `User` and `Organization`, not on the `Repository` level, and there would definitely be a case where a user is sponsorable but not on every Go packages that they released.

Hope you guys have a great week ahead! :grinning:

**Comment by mholt** [comment]
@joshuabezaleel Hi! :wave: Thank you for your kind remarks! And thanks for replying of course. 😁 

> By querying, do you folks mean accessing via the REST API and parsing the content of the .github/FUNDING.yml file on each of the repositories?

It would be ideal if the API had that information for repositories, yes, but...

>  I tried to dig in to the GitHub GraphQL API and found out that Sponsorable is implemented only on User and Organization, not on the Repository level, and there would definitely be a case where a user is sponsorable but not on every Go packages that they released.

... I guess that's not the case. Directly. You _could_ probably query the repo via the API to get its owner / organization, and then query the user or organization to see if they are Sponsorable.

Or, a better solution might be to see if the project has a [funding.yml](https://help.github.com/en/github/building-a-strong-community/displaying-a-sponsor-button-in-your-repository#about-funding-files) file in it. That will give you richer information than the API or scraping the page, I bet.

**Comment by joshuabezaleel** [comment]
@mholt 
> Or, a better solution might be to see if the project has a funding.yml file in it. That will give you richer information than the API or scraping the page, I bet.

I think this (accessing and parsing the funding.yml) is achieveable by using [this endpoint](https://developer.github.com/v3/repos/contents/#get-contents) to access the repo's content but what is troubling me by not using the list is how to link the projects/repos/packages to its particular authors, so that it can be grouped according to authors. For example, putting `caddy` and `archiver` under your name `mholt`, and not separated to different author `caddyserver` and `mholt`. Or do you think that that was not a necessary thing to do in this multi-repo case? 

![image](https://user-images.githubusercontent.com/7043511/69121337-acfca280-0ace-11ea-8d92-7186e06e849f.png)

Also, the sponsor link of Caddy at the README redirecting to the [pricing page](https://caddyserver.com/pricing) is broken. You might want to fix that :grin: .

**Comment by mholt** [comment]
@joshuabezaleel That works -- looks good to me!

> Also, the sponsor link of Caddy at the README redirecting to the pricing page is broken. You might want to fix that 😁 .

Oops, yeah. Will get around to that... thanks

**Comment by joshuabezaleel** [comment]
Hi @mholt , I just tried to rewrote the package inspired by our conversation before. Thank you very much for the awesome inputs! :slightly_smiling_face: 
I tried to retrieve each of the repositories' `FUNDING.yml` and then grouped it according to the author by the first (1st) GitHub Sponsors-enabled username provided in the file. 

If it's okay with you, I would like for you to try the newer version and looking forward to your input! Thank you very much and have a nice day ahead! :smile:

**Comment by mholt** [comment]
Awesome! I just tried it out, and this is the output, running for the Caddy repo:

```
$ go-support 
🕘 Retrieving data from GitHub
github.com/caddyserver/caddy/v2
.
├── 
│   ├── package(s)
│   │   └── github.com/imdario/mergo
│   └── donation urls
│       ├── Kofi: https://ko-fi.com/dariocc
│       └── Custom: https://beerpay.io/imdario/mergo
└── mholt
    ├── package(s)
    │   └── github.com/mholt/certmagic
    └── donation urls
        └── GitHub: https://github.com/sponsors/mholt
```

I like the little clock animation.

It seems that one of the usernames is empty. (I'm also surprised that there's only 1 other user(?) that accepts sponsors! But I guess that's not too surprising since GitHub Sponsors is fairly new.)

But, I really like where this is going!

Oh, and the browser windows didn't open up for me.

**Comment by joshuabezaleel** [comment]
@mholt Thank you for trying it out, Matt! :slightly_smiling_face: 
Yeah, sadly there are still only few authors with GitHub Sponsors enabled. Hope there will be so much more in the future. 

Whoops, thank you for the bug report. Will dig in to the that bug ASAP :/ 

Also, regarding the browser, what kind of OS are your machine using? Is it Windows?

**Comment by mholt** [comment]
Sorry, forgot those details: MacOS Mojave.

**Comment by joshuabezaleel** [comment]
Can't seem to find what caused the error at the previous one since I tried this at my friend's MacOS and it worked :confused: but I now use [pkg/browser](https://github.com/pkg/browser) to handle the opening the browser process. Hope this works now.

**Comment by mholt** [comment]
I just tried it again (at the same commit) and it works fine, but you have to use uppercase `Y`, whereas the first time I used `y` (lowercase). What you had before (`openbrowser()`) is just fine I think.

**Comment by joshuabezaleel** [comment]
Handled the lowercase `y`. Thank you very much for the really helpful inputs, @mholt !! :slightly_smiling_face:
